// URI
export const API_URI = 'https://server-express-foodapp.herokuapp.com/api';

// category
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_LOADED_SUCCESS = 'CATEGORY_LOADED_SUCCESS';
export const CATEGORY_LOADED_FAIL = 'CATEGORY_LOADED_FAIL';
export const CATEGORY_SENT = 'CATEGORY_SENT';
export const CATEGORY_SENDING = 'CATEGORY_SENDING';
// export const GET_CATEGORY = 'GET_CATEGORY';

// restauratn
export const RESTAURANT_LOADING = 'RESTAURANT_LOADING';
export const RESTAURANT_LOADED_SUCCESS = 'RESTAURANT_LOADED_SUCCESS';
export const RESTAURANT_LOADED_FAIL = 'RESTAURANT_LOADED_FAIL';
export const RESTAURANT_SENT = 'RESTAURANT_SENT';
export const RESTAURANT_SENDING = 'RESTAURANT_SENDING';
export const RESTAURANT_CATEGORY_SUCCESS = 'RESTAURANT_CATEGORY_SUCCESS';
export const RESTAURANT_CATEGORY_FAIL = 'RESTAURANT_CATEGORY_FAIL';
export const RESTAURANT_HAVERSINE_SUCCESS = 'RESTAURANT_HAVERSINE_SUCCESS';
export const RESTAURANT_SEARCH_SUCCESS = 'RESTAURANT_SEARCH_SUCCESS';
// export const GET_RESTAURANT = 'GET_RESTAURANT';

// food
export const FOOD_LOADING = 'FOOD_LOADING';
export const FOOD_LOADED_SUCCESS = 'FOOD_LOADED_SUCCESS';
export const FOOD_LOADED_FAIL = 'FOOD_LOADED_FAIL';
export const FOOD_SENT = 'FOOD_SENT';
export const FOOD_SENDING = 'FOOD_SENDING';
// export const GET_FOOD = 'GET_FOOD';

// menu
export const MENU_LOADING = 'MENU_LOADING';
export const MENU_LOADED_SUCCESS = 'MENU_LOADED_SUCCESS';
export const MENU_LOADED_FAIL = 'MENU_LOADED_FAIL';
export const MENU_SENT = 'MENU_SENT';
export const MENU_SENDING = 'MENU_SENDING';
// export const GET_MENU = 'GET_MENU';

// auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_FAIL = 'USER_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REG_LOADING = 'REG_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOG_LOADING = 'LOG_LOADING';
// export const SET_AUTH = 'SET_AUTH';
// export const LOCAL_STORAGE_TOKEN_NAME = 'LOCAL_STORAGE_TOKEN_NAME';

// cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECK_OUT = 'CHECK_OUT';
// export const SET_CART = 'SET_CART';

// error
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// combo
export const COMBO_LOADING = 'COMBO_LOADING';
export const COMBO_LOADED_SUCCESS = 'COMBO_LOADED_SUCCESS';
export const COMBO_LOADED_FAIL = 'COMBO_LOADED_FAIL';
export const COMBO_SENT = 'COMBO_SENT';
export const COMBO_SENDING = 'COMBO_SENDING';

// choose
export const CHOOSE_LOADING = 'CHOOSE_LOADING';
export const CHOOSE_LOADED_SUCCESS = 'CHOOSE_LOADED_SUCCESS';
export const CHOOSE_LOADED_FAIL = 'CHOOSE_LOADED_FAIL';
export const CHOOSE_SENT = 'CHOOSE_SENT';
export const CHOOSE_SENDING = 'CHOOSE_SENDING';

export const LISTCHOOSE_LOADING = 'LISTCHOOSE_LOADING';
export const LISTCHOOSE_LOADED_SUCCESS = 'LISTCHOOSE_LOADED_SUCCESS';
export const LISTCHOOSE_LOADED_FAIL = 'LISTCHOOSE_LOADED_FAIL';
export const LISTCHOOSE_SENT = 'LISTCHOOSE_SENT';
export const LISTCHOOSE_SENDING = 'LISTCHOOSE_SENDING';

/// Cart food and combo
export const CART_LOADED_SUCCESS = 'CART_LOADED_SUCCESS';
export const CART_LOADED_FAIL = 'CART_LOADED_FAIL';
export const ORDER_LOADED_SUCCESS = 'ORDER_LOADED_SUCCESS';
export const ORDER_LOADED_FAIL = 'ORDER_LOADED_FAIL';

// pay
export const PAY_LOADED_SUCCESS = 'PAY_LOADED_SUCCESS';
export const PAY_LOADED_FAIL = 'PAY_LOADED_FAIL';

// tính khoảng cách
export const HAVERSINE_LOADED_SUCCESS = 'HAVERSINE_LOADED_SUCCESS';
export const HAVERSINE_LOADED_FAIL = 'HAVERSINE_LOADED_FAIL';

// lịch sử order
export const ORDER0_LOADED_SUCCESS = 'ORDER0_LOADED_SUCCESS';
export const ORDER0_LOADED_FAIL = 'ORDER0_LOADED_FAIL';

export const ORDER1_LOADED_SUCCESS = 'ORDER1_LOADED_SUCCESS';
export const ORDER1_LOADED_FAIL = 'ORDER1_LOADED_FAIL';

export const ORDER2_LOADED_SUCCESS = 'ORDER2_LOADED_SUCCESS';
export const ORDER2_LOADED_FAIL = 'ORDER2_LOADED_FAIL';

export const ORDER3_LOADED_SUCCESS = 'ORDER3_LOADED_SUCCESS';
export const ORDER3_LOADED_FAIL = 'ORDER3_LOADED_FAIL';

export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';

// action props
// export const ActionProps = {
//   type: any,
//   payload: any | void,
// };
